server:
  port: 8082
  session:
    cookie:
      name: UISESSION
spring:
  thymeleaf:
    cache: false
  oauth2:
    client:
      registration:
        custom-client:
          client-id: {yourClientId}
          client-secret: {yourClientSecret}
          client-name: Auth Server
          scope: user_info
          provider: custom-provider
          redirect-uri-template: http://localhost:8082/login/oauth2/code/
          client-authentication-method: basic
          authorization-grant-type: authorization_code
      provider:
        custom-provider:
          token-uri: http://localhost:8081/auth/oauth/token
          authorization-uri: http://localhost:8081/auth/oauth/authorize
          user-info-uri: http://localhost:8081/auth/user/me
          user-name-attribute: name

